services:
  backend:
    build:
      dockerfile: ./go-dev.Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file: "dev.env"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: manavore
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
