services:
  backend:
    build:
      dockerfile: ./go-dev.Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file: "dev.env"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: manavore
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: manavore
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: dev-file
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/

volumes:
  minio_data:
  keycloak_data:
